[package]
name = "crabweb"
version = "0.1.0"
authors = ["Max Gonzih <gonzih@gmail.com>"]
edition = "2018"

[dependencies]
crabquery = "0.1.3"
reqwest = { version = "0.10", features = [] }
async-std = { version = "1.5.0", features = ["unstable"] }
tokio = { version = "0.2.11", features = ["full"] }
futures = "0.3.4"
async-trait = "0.1.24"
crabweb_derive = { path = "./crabweb_derive" }
