[package]
name = "crabweb_derive"
version = "0.1.0"
authors = ["Max Gonzih <gonzih@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.15"
quote = "1.0"
proc-macro-error = "0.4.9"
proc-macro2 = "1.0"
