name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nixos/nix
    steps:
    - uses: actions/checkout@v2
    - name: Nix Channel Update
      run: nix-channel --update
    - name: CI
      run: nix-shell shell.nix --run 'make rust-setup test'
